default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: blog_development
  pool: 25

test:
  <<: *default
  database: blog_test
  pool: 25
